# -*- coding: utf-8 -*-
"""Day2-AI-ML-DL.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LeAa9HjThqPAghWau-saTWYoHJBMg7-x

**Artificial Intelligence (AI)**

Definition: AI refers to the development of computer systems that can perform tasks that typically require human intelligence. These tasks include problem-solving, learning, perception, understanding natural language, and speech recognition.
Scope: AI is a broad field that encompasses various approaches, including rule-based systems, expert systems, symbolic reasoning, and machine learning. It can be categorized into two types: Narrow AI (or Weak AI), which is designed for a specific task, and General AI (or Strong AI), which aims to replicate human-like intelligence across a wide range of tasks.


Artificial Intelligence (AI) can be categorized into different types based on its capabilities and functionalities. Here are some common types of AI:

Narrow AI (Weak AI):

Definition: Narrow AI refers to AI systems that are designed and trained for a specific task. These systems excel in performing a particular function but lack the broad cognitive abilities associated with human intelligence.
Example: Virtual personal assistants like Siri or Alexa, image recognition software, and chatbots are examples of narrow AI.
General AI (Strong AI):

Definition: General AI, also known as Strong AI, refers to a type of artificial intelligence that possesses the ability to understand, learn, and apply intelligence across a wide range of tasks, similar to human intelligence.
Status: General AI is still a theoretical concept and has not been achieved. Researchers are working on developing systems with more generalized cognitive abilities.
Artificial Narrow Intelligence (ANI):

Definition: Artificial Narrow Intelligence is another term for Narrow AI. It denotes AI systems that are designed for and excel in a specific task or a narrow set of tasks.
Artificial General Intelligence (AGI):

Definition: Artificial General Intelligence is synonymous with General AI. It represents AI systems that possess human-like cognitive abilities and can perform any intellectual task that a human being can.
Superintelligent AI:

Definition: Superintelligent AI refers to an artificial intelligence system that surpasses human intelligence in virtually every aspect, including problem-solving, creativity, and emotional understanding.
Caution: The concept of superintelligent AI often comes with ethical and existential concerns, as it implies an AI system with capabilities far beyond human understanding.
Machine Learning AI:

Definition: Machine Learning AI refers to AI systems that utilize machine learning algorithms to learn from data and improve their performance over time.
Example: Many practical AI applications, such as image recognition, natural language processing, and recommendation systems, are built using machine learning.
Reactive Machines:

Definition: Reactive Machines are AI systems that operate based on predefined rules and respond to specific inputs. They don't have the ability to learn or adapt from new information.
Example: Chess-playing programs that follow a set of predefined rules to make moves without learning from previous games.
These types of AI represent different levels of intelligence and capabilities. While Narrow AI is prevalent in today's applications, achieving General AI or Superintelligent AI remains a goal for future research and development.

## ***Machine Learining ***

Machine Learning (ML):

Definition: Machine Learning is a subset of AI that focuses on the development of algorithms and statistical models that enable computers to perform tasks without explicit programming. ML algorithms learn patterns from data and make predictions or decisions based on that learning.
Approaches: ML can be categorized into three main types:
Supervised Learning: Algorithms are trained on labeled data, making predictions or decisions based on that training.
Unsupervised Learning: Algorithms work with unlabeled data to discover patterns or relationships without explicit guidance.
Reinforcement Learning: An agent learns by interacting with an environment and receiving feedback in the form of rewards or

# ***Deep Learning (DL)***

Definition: Deep Learning is a specialized subset of machine learning that involves neural networks with multiple layers (deep neural networks). These networks, often referred to as artificial neural networks, attempt to mimic the structure and function of the human brain.
Architecture: Deep Learning architectures, such as Convolutional Neural Networks (CNNs) for image recognition and Recurrent Neural Networks (RNNs) for sequence data, have demonstrated remarkable success in tasks like image and speech recognition, natural language processing, and playing complex games.
Training: Deep Learning models require a large amount of labeled data for training and powerful computational resources, often utilizing GPUs or specialized hardware.
In summary, AI is the overarching concept focused on creating intelligent machines, ML is a subset of AI that emphasizes learning from data, and DL is a subset of ML that specifically involves neural networks with multiple layers. While AI encompasses a wide range of approaches beyond machine learning, and machine learning encompasses various algorithms, deep learning is a specific type of machine learning that relies on deep neural networks.
"""

