# -*- coding: utf-8 -*-
"""day5Online vs offline Learning.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MeQqDFsP6UC4IXkb-G6aYdNMc3UX7gZw

Online Learning vs. Offline Learning:

Online Learning:

Definition: In the context of machine learning, online learning refers to a learning process where the model is updated continuously as new data becomes available.

Characteristics:
1. Model is updated in real-time as data streams in.
2. Suited for scenarios with dynamic data or when the model needs to adapt to changes over time.


Offline Learning:

Definition: Offline learning, or batch learning, involves training the model on a fixed dataset, and the model is not updated once the training phase is complete.

Characteristics:
1. The model is trained on a static dataset.
2. Once trained, the model is applied to new data without further updates.

Online Machine Learning:

Definition: Online machine learning is a broader concept that encompasses both online learning and offline learning. It refers to the capability of a machine learning system to adapt and learn continuously from new data (online learning) or to be trained on a fixed dataset (offline learning).

Characteristics:
1.
Can refer to systems that adapt to new data in real-time or systems trained on a static dataset.

Offline Machine Learning:

Definition: This term is not commonly used, as machine learning models are often trained offline initially, and then the trained models are applied to new data.

Characteristics:
1. The model is typically trained on a predefined dataset during a training phase.
"""

