# -*- coding: utf-8 -*-
"""day6 instance based | model based Learning.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MC13umwQXiKVoqGXR8EuUWx2wXHyd338

Instance-Based Learning:

Definition: Instance-based learning, or instance-based methods, refers to machine learning approaches that make predictions based on specific instances or examples from the training data.

Characteristics:
1. The model doesn't explicitly learn a general rule or hypothesis during the training phase.
2. Instead, it memorizes the training instances and uses them to make predictions on new, unseen instances.
3. Common examples include k-Nearest Neighbors (k-NN) algorithms, where predictions are based on the majority class of the k-nearest training instances.

Model Based Learning

Definition: Model-based learning involves training a model to learn a generalized representation or function that maps input features to the target output.

Characteristics:
`1. The model captures the underlying patterns or relationships in the training data.
2. After training, the model can make predictions on new, unseen instances by applying the learned rules or functions.
Examples include linear regression, decision trees, and neural networks.
"""

