# -*- coding: utf-8 -*-
"""day7 challenges in machine Learning.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1muA6GYJbhTWn3QfZcRTYBiwUt6mTmNf4

Problmes faced in the field of machine learning:

Inaccurate, incomplete, or biased data can lead to poor model performance.

2. DataQuantity:
Insufficient data can limit the ability of models to generalize well.

3. Feature Selection:
Choosing relevant features and dealing with high-dimensional data can be challenging.

4. Underfitting:
Overly simple models may fail to capture the underlying patterns in the data.

5. Comutational Resources:
TRaining complex models can be computationally intensive and time- consuming.

6. Interpretabality:
Understanding and interpreting the decisions made by complex models, especially in sensitive applications, is challenging.

7. Lack of Standardization:
lack of standardization evealuation metrices and methodologies can make it difficult to compare models and reaults.

8. Algorithem Bias:
Model can inherit biases to handle large datasets and growing computational demands is a continual challenge.


9. TRansfer Learning:
Applying knowledge classes or outcomes are underrprented, modles may struggle to predict to predict monaority classes accurately.
"""

