# -*- coding: utf-8 -*-
"""day 15 working with csv.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PsUCR7a7upOGAX0TXdYHv_xNy20V2AwC

1. importing  pandas
"""

import pandas as pd

"""2.Opening a local csv file"""

df=pd.read_csv("aug_train.csv")
df

"""Opening a csv file from an URl"""

import requests
from io import StringIO

url = "https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv"
headers = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0"}
req = requests.get(url, headers=headers)
data = StringIO(req.text)

pd.read_csv(data)

"""4 Sep Parameters"""

pd.read_csv("/content/movie_titles_metadata.tsv",sep="\t",names=["sno","name","release_year","rating","votes","genres"])

"""5. Index_col parameter"""

pd.read_csv("aug_train.csv",index_col="enrollee_id")

"""6. Header parameter"""

pd.read_csv('test.csv',header=1)

"""7. use_cols parameters"""

pd.read_csv("aug_train.csv",usecols=['enrollee_id','gender','education_level'])

"""8. Sequeeze parameters"""

from collections.abc import Sequence
pd.read_csv("aug_train.csv",usecols=["gender"],squeeze=True)

"""9.Skipprows/nrows parameter"""

pd.read_csv("aug_train.csv",nrows=100)

"""10.Encoding parameter"""

pd.read_csv("zomato.csv",encoding="latin-1")

"""11.skip bad lines

12 dtypes parameter
"""

pd.read_csv('aug_train.csv',dtype={'target':int}).info()

"""13. Handling Dates"""

pd.read_csv('IPL Matches 2008-2020.csv',parse_dates=['date']).info()

def rename(name):
  if name=="Royal Challengers Bangalore":
    return "RCB"
  else:
    return name

rename("Royal challengers Bangalore")

"""!$ converters"""

pd.read_csv('IPL Matches 2008-2020.csv',converters={'team1':rename})

"""15.na_value parmeters"""

pd.read_csv("aug_train.csv",na_values=["Male",])

"""16 Loading the a huge dataset in chunks"""

